# Generated by Django 4.1.2 on 2023-06-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevousuario',
            name='contrasena',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
