# Generated by Django 4.1.2 on 2023-06-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_nuevousuario_contrasena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodista', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('palabra_clave', models.CharField(max_length=50)),
            ],
        ),
    ]
