# Generated by Django 4.1.2 on 2023-06-24 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0003_categoria_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='formCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='idCategoria',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nuevousuario',
            name='idUsuario',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='usuarios.categoria'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='idPublicacion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='idUsuario',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='imagen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones_autor', to=settings.AUTH_USER_MODEL),
        ),
    ]
